spring.application.name=Darts Backend

spring.datasource.url=jdbc:postgresql://[SERVER]:5432/darts
spring.datasource.username=postgres
spring.datasource.password=[PASSWD]
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Darts
com.jpromi.darts.files.path=files
com.jpromi.darts.api.domain=https://darts.jpromi.com
